export interface IApplicationDetailed {
    firstName: string,
    lastName: string,
    age: number,
    gender: string,
    contactNo: number,
    emailId: string,
    address: string,
    state: string,
    city: string,
    pincode: number,
    userId: string,
    customerId: number,
    typeOfEmployement: string,
    yearlySalary: number,
    existingEmi: number,
    loanId: number,
    loanAmount: number,
    loanTenure: number,
    loanInterestRate: number,
    accountType: string,
    processingFee: number,
    vehicleId: number,
    carMake: string,
    carModel: string,
    exshowroomPrice: number,
    onroadPrice: number,
    statusId: number
}

